"""empty message

Revision ID: 764b513a3a79
Revises: 30436ed0ecca
Create Date: 2025-03-24 11:57:47.786151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764b513a3a79'
down_revision = '30436ed0ecca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
